-- 018_character_appearance: the narrative appearance/description of a character,
-- set/regenerated by the Rook body-modification service (bodyMod / respec). Without
-- this column, saving a REMADE character fails (toRow writes `appearance`), which
-- silently dropped the whole character upsert — HP, credits, and the remake itself.
alter table characters add column if not exists appearance text;
