import Anthropic from "@anthropic-ai/sdk";
import type { CampaignState } from "@/shared/schemas";
import { liveRng, type RNG, type EngineEvent } from "@/engine";
import { combatActions, type CombatState, type CombatAction, type CombatOutcome } from "@/shared/combat";
import { usableConsumables } from "@/shared/items";
import { TurnRuntime } from "./engineBridge";
import type { MemberOrder } from "./combat/types";
import { deepseekChat, deepseekChatStream, isDeepSeekModel, resolveModel } from "./deepseek";
import { sanitizeHistory } from "./history";
import { stripInlineMenu } from "@/shared/narration";
import type { ChoiceOption } from "@/shared/turnPlan";
import { graduatedTutorialThisTurn } from "@/shared/tutorial";

/**
 * Ongoing-combat turn handler. Combat is ENGINE-OWNED: the engine resolves the
 * round (player action → enemy volley → end check), and the model is used ONLY
 * to narrate the already-decided results. Combat action chips are generated by
 * the engine, never the model — so DeepSeek cannot derail a fight.
 */

export interface CombatTurnInput {
  state: CampaignState;
  combat: CombatState;
  history: Anthropic.MessageParam[];
  action: CombatAction;
  /** Squad orders for standing crew/allies (HANDOFF_COMBAT_V2_1 Task C) — a
   *  member with no matching order here keeps crewPhase's auto-act. */
  crewOrders?: MemberOrder[];
  /** The player's raw typed action (when they didn't click a chip) — woven into
   *  the narration for flavor, but the engine numbers are final. */
  playerText?: string;
  tickedSet?: Set<string>;
  model?: string;
  rng?: RNG;
  apiKey?: string;
  onDelta?: (text: string) => void;
  onEngine?: (lines: string[]) => void;
}

export interface CombatTurnResult {
  narration: string;
  choices: ChoiceOption[];
  combat: CombatState | null;
  engineLines: string[];
  outcome: CombatOutcome;
  state: CampaignState;
  events: EngineEvent[];
  worldEvents: TurnRuntime["worldEvents"];
  sceneEnded: boolean;
  /** Combat turns never close a narrative scene themselves. */
  sceneTitle: string | null;
  focusIds: string[];
  tutorialGraduated: boolean;
  model: string;
  promptDump: string;
  exchangeDump: string;
  usage: { inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheWriteTokens: number };
  telemetry: { latencyMs: number; rounds: number; toolCalls: string[]; stopReason: string; fellBack: boolean; systemChars: number };
}

const COMBAT_SYSTEM = `You are the DM narrating ONE round of a brutal space-opera firefight. You are given the round's ENGINE RESULTS — already-decided rolls, hits, misses, damage, who went down. Write 2-3 vivid sentences, second person, present tense, describing what happens. Honor the numbers EXACTLY: never invent a hit, a miss, damage, or a death the results don't show. Do NOT list options, do NOT ask questions, do NOT write dice notation. Just the action.`;

/** Post-combat chips (a fresh normal turn follows next). */
function endChoices(outcome: CombatOutcome): ChoiceOption[] {
  if (outcome === "dead") return [];
  if (outcome === "victory") return [{ label: "Search the wreckage" }, { label: "Move on" }];
  if (outcome === "escaped") return [{ label: "Catch your breath" }, { label: "Keep moving" }];
  if (outcome === "disabled") return [{ label: "Assess the damage" }, { label: "Signal for help" }];
  // Downed → the route swaps in the engine-generated Bleeding Out chips (it has the
  // held consumables + who's present); no dead-end "Take stock" button anymore.
  return [];
}

export async function runCombatTurn(input: CombatTurnInput): Promise<CombatTurnResult> {
  const model = resolveModel(input.model ?? resolveModel(process.env.NARRATOR_MODEL ?? "deepseek-v4-flash"));
  let activeModel = model;
  let fellBack = false;
  const startedAt = Date.now();
  const usage = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 };

  const runtime = new TurnRuntime(input.state, input.rng ?? liveRng, { tickedThisScene: input.tickedSet });

  // 1. Resolve the round in the engine — the PC's action plus any staged
  // squad orders (HANDOFF_COMBAT_V2_1 Task C); un-ordered members auto-act.
  const pcId = runtime.state.characters.find((c) => c.kind === "pc")?.id ?? "";
  const orders: MemberOrder[] = [{ memberId: pcId, action: input.action }, ...(input.crewOrders ?? [])];
  const { combat: nextCombat, lines, outcome, loot } = runtime.resolveCombatRound(input.combat, orders);
  input.onEngine?.(lines);
  void loot;

  const pc = runtime.state.characters.find((c) => c.kind === "pc");
  const consumables = pc ? usableConsumables(pc, nextCombat.scale) : [];
  const burstReady = !!runtime.state.ship?.burstDriveReady;
  const weaponNames = (pc?.gear ?? []).filter((g) => g.damage).map((g) => g.name);

  // 2. Narrate the round from the engine results (model narrates only).
  const status =
    outcome === "continue"
      ? `Round ${nextCombat.round}. Enemies left: ${nextCombat.enemies.map((e) => `${e.name} ${e.hp}/${e.maxHp}`).join(", ") || "none"}.`
      : `Combat ${outcome}.`;
  const intent =
    input.playerText?.trim() && !/^(attack|fire on|take aim|take cover|flee|use |divert|throw|pop )/i.test(input.playerText.trim())
      ? `The player tried to: "${input.playerText.trim()}". Flavor the round around that intent, but the ENGINE RESULTS above are what actually happened — honor them exactly.\n`
      : "";
  const messages: Anthropic.MessageParam[] = [
    ...sanitizeHistory(input.history),
    { role: "user", content: `COMBAT ROUND — ENGINE RESULTS:\n${lines.join("\n")}\n\n${status}\n${intent}Narrate this round.` },
  ];
  const system: Anthropic.TextBlockParam[] = [{ type: "text", text: COMBAT_SYSTEM }];
  const promptDump = `=== SYSTEM ===\n${COMBAT_SYSTEM}\n\n=== ENGINE ===\n${lines.join("\n")}\n${status}`;

  let raw = "";
  let stopReason = "end_turn";
  try {
    if (isDeepSeekModel(activeModel)) {
      // 800 not 300: hybrid DeepSeek models may spend tokens thinking before the
      // visible prose; headroom keeps a thinking pass from truncating the round.
      const params = { model: activeModel, maxTokens: 800, system, messages };
      const resp = input.onDelta
        ? await deepseekChatStream({ ...params, onDelta: (t) => input.onDelta!(t) })
        : await deepseekChat(params);
      usage.inputTokens += resp.usage.input_tokens;
      usage.outputTokens += resp.usage.output_tokens;
      usage.cacheReadTokens += resp.usage.cache_read_input_tokens;
      stopReason = resp.stop_reason;
      raw = resp.content.filter((b) => b.type === "text").map((b) => (b as { text: string }).text).join("");
    } else {
      const anthropic = new Anthropic({ apiKey: input.apiKey ?? process.env.ANTHROPIC_API_KEY });
      const resp = await anthropic.messages.create({ model: activeModel, max_tokens: 300, system, messages });
      usage.inputTokens += resp.usage.input_tokens;
      usage.outputTokens += resp.usage.output_tokens;
      stopReason = resp.stop_reason ?? "end_turn";
      raw = resp.content.filter((b) => b.type === "text").map((b) => (b as { text: string }).text).join("");
    }
  } catch (err) {
    // Combat must never wedge on a narration failure — fall back to a terse line.
    if (isDeepSeekModel(activeModel) && process.env.ANTHROPIC_API_KEY) fellBack = true;
    console.error("[combatTurn] narration failed:", err instanceof Error ? err.message : err);
    raw = status;
  }
  const narration = stripInlineMenu(raw.trim()) || status;

  const choices =
    outcome === "continue" && nextCombat.active ? combatActions(nextCombat, consumables, burstReady, weaponNames) : endChoices(outcome);

  return {
    narration,
    choices,
    combat: nextCombat.active ? nextCombat : null,
    engineLines: lines,
    outcome,
    state: runtime.state,
    events: runtime.events,
    worldEvents: runtime.worldEvents,
    sceneEnded: false,
    sceneTitle: null,
    focusIds: [],
    tutorialGraduated: graduatedTutorialThisTurn(input.state, runtime.state),
    model: activeModel,
    promptDump,
    exchangeDump: [...lines, `[NARRATION]\n${raw}`].join("\n\n"),
    usage,
    telemetry: {
      latencyMs: Date.now() - startedAt,
      rounds: 1,
      toolCalls: ["combat_round", `combat_${input.action.type}`],
      stopReason,
      fellBack,
      systemChars: COMBAT_SYSTEM.length,
    },
  };
}
